Rename ah.{ tokenize => tokenizer } to prevent naming conflicts
See GitHub python workflow issue:
    ...
    File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
    AttributeError: module 'tokenize' has no attribute 'open'